name: Build
on:
  watch:
    types: [started]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
#第一步，配置go环境
      - name: Setup Go 1.19
        uses: actions/setup-go@v3
        with:
          check-latest: true
          go-version: '1.19'
#第二步，克隆代码
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
#第三步，go build
      - name: Build
        run: |
          go get
          go build .
#上传文件
      - name: Upload
        uses: actions/upload-artifact@main
      #  if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./*
     #     draft: true
